/*
 * This source file was generated by the Gradle 'init' task
 */
package taller5;

public class App {
    
    public static void main(String[] args) {
        
        try {
            System.out.println(num_alea(1250));
            System.out.println(Simular_ventas());
            System.out.println(Calcular_empaque(2000));
            System.out.println(Jugar_21(6));
        } 
        
        catch (Exception e) {
            // TODO: handle exception
        }
    }


    /*
    
        1.	Desarrolle un algoritmo e impleméntelo en Java que: le pida al usuario un número entero positivo 
        entre 1000 y 9999. En un ciclo genere números de manera aleatoria y cuente los intentos que hizo antes 
        de hallar el número exactamente.
        
    
    */ 

    public static int num_alea (int num){
        try {
            final int lim_inf = 1000, lim_sup = 9999;
            int alea = 0;
            int cont_num = 0;

            if(num>=lim_inf && num<=lim_sup){   

                while(alea!=num){

                    for(int n=1; n<=num; n++){
                        alea = (int)((Math.random()*(9999-1000)+1000));
                        cont_num++;
                        if(alea==num)
                            break;
                    }
                }
                return cont_num;  
            }  
            else
                return 0; 
        } 
        catch (Exception e) {
            return -1;
        }
    }




    /* 
     
        2.	Se requiere una función en java que simule las ventas de tres años para un almacén. Para cada año, deberá generar 
        un aleatorio para cada mes hasta completar los 12 meses. La función se llamará Simular_ventas, y debe retornar un String 
        al final que muestre las ventas de cada año, así:
        
            Año 1
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total ventas Año 1:  $##.###.###
            
            Año 2
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total ventas Año 2: $##.###.###
            
            Año 3
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###

            Total ventas Año 3: $##.###.###
            
            Investigue sobre la clase DecimalFormat para mostrar bien la salida. 
            import java.text.DecimalFormat;
            DecimalFormat form_pesos = new DecimalFormat("$#,###.00");

        
      
    */

    public static String Simular_ventas(){
        try {
            final byte ano_final = 3;
            final byte mes_final = 12;
            DecimalFormat form_pesos = new DecimalFormat("$#,###.00");
            int ventas;
            String info_ventas = "";
            int suma_ventas;

            for(int ano=1; ano<=ano_final; ano++){
                info_ventas = "\n" + info_ventas + "Año " + ano;
                suma_ventas = 0;

                for(int mes=1; mes<=mes_final; mes++){
                    ventas = (int)((Math.random()*(99999-0)+0));
                    info_ventas = info_ventas + "\n Ventas mes " + mes + ":" + form_pesos.format(ventas);
                    suma_ventas = suma_ventas + ventas;
                }
                info_ventas = info_ventas + "\n Total ventas Año " + ano + ":" + form_pesos.format(suma_ventas) + "\n";
            }
            return info_ventas;
        } 
        catch (Exception e) {
            return "Error";
        }     
    }

    



    /*  
     
        3.	En una fábrica se tiene el siguiente patrón de empaque: En una estiba(o pallet) caben 16  cajas y en cada caja, 
        caben 30 bombillas. Desarrolle una función que se llame: Calcular_empaque que: reciba como argumento la cantidad de 
        bombillas que se deben empacar y a partir de allí: calcule cuántas cajas necesita, cuántas estibas o pallets necesita. 
        Luego escriba lo siguiente: 

        Para ### bombillas, se necesitan ## cajas y ## pallets. Se quedan ### bombillas sin empacar. Se empacará así:

        Pallet 1 --> Caja1, Caja2……,Caja16
        Pallet2 -->  Caja17, Caja18…..Caja 32
        .
        Pallet n -- > Caja m, caja m+1…..
        
        La función retornará un texto, con la información anterior. Pruebe la función llamándola desde el programa principal: solicite al usuario el número de bombillas e invoque la función para imprimir en el main, los resultados.



    */

    public static String Calcular_empaque (int cant_bombillas){
        try {
            final int cajas_x_pallet = 16;
            final int bomb_x_cajas = 30;
            int cajas_necesarias =  cant_bombillas/bomb_x_cajas;
            int pallet_necesario = cajas_necesarias/cajas_x_pallet;
            String empaques = "Para " + cant_bombillas + " bombillas, se necesitan " + cajas_necesarias + " cajas y " + pallet_necesario + " pallets\n";

            for(int pallet=1; pallet<=pallet_necesario; pallet++){
                empaques += "Pallet " + pallet + " -->";

                for(int cajas=1; cajas<=cajas_necesarias; cajas++){
                    empaques += "Caja " + cajas + ", ";
                }
                empaques += "\n";
            }
            return empaques;
        } 
        catch (Exception e) {
            return "Error";
        }
    }



    

    /* 
    

        4.	En un juego, cada jugador tiene 3 intentos para sacar cartas de una baraja. Las cartas van numeradas entre 1 y 10. 
        Una función Jugar_21, deberá simular el juego para una cantidad de usuarios que enviará el usuario desde el main entre 1 y 6.

        Para cada uno de los jugadores, el programa le calculará 3 cartas al azar y al final imprimirá el juego para cada jugador basado en las siguientes reglas: 
        
        Si saca 21 exactos: juego perfecto
        Si saca más de 21: se pasó
        Si saca menos de 21: faltaron puntos

        La función deberá imprimir los puntos de cada jugador junto con la regla anterior, como muestra el ejemplo:

        Jugador X, puntos 21 -- > juego perfecto
        Jugador Y, puntos 26 -- > se pasó
        .
        .


    */

    public static String Jugar_21 (int usuarios){
        try {
            final byte total_cartas = 3;
            int carta_random;
            int puntos;
            String juego;
            int juga;
            String jugadores = "";

            for(int jugador=1; jugador<=usuarios; jugador++){
                juga = jugador;
                puntos = 0;

                for(int cartas=1; cartas<=total_cartas; cartas++){
                    carta_random = (int)((Math.random()*(10-1)+1));
                    puntos += carta_random;
                }
                if(puntos>21)
                    juego = "Se pasó";
                else if(puntos==21)
                    juego = "Juego perfecto";
                else
                    juego = "Faltaron puntos";
                jugadores += "Jugador " + juga + ", puntos " + puntos + " --> " + juego + "\n";   
            }
            return jugadores;
        } 
        catch (Exception e) {
            return "Error";
        }
    }



}
